### ISSUE TITLE
Error: Future resolved more than once

### ISSUE THREAD

**Issue by borodyadka** [chadpaulson/react-isomorphic-video-game-search#1]
Hi, there is a problem with reflux.
When i open a details page (e.g. [Mario Bros.](http://localhost:4000/game/19726/mario-bros))
 in console shows `[Error: Future resolved more than once]`. If i reload page then shows two messages, then three and so on.
[There](https://github.com/chadpaulson/react-isomorphic-video-game-search/blob/9e10d206f6021b963bb6e5a0637dd54d9e653091/react/src/game.jsx#L22) is a place with bug.
Any ideas how to fix it?

Sorry for my bad english.

**Comment by andre0799** [comment]
I'm getting the same error and if it affects the performance I would like to know how to fix

**Comment by chadpaulson** [comment]
This is an unfortunate byproduct of react-async, which requires node-fibers, when initializing state for the same component asynchronously multiple times.

I have been researching better ways of solving the problems outlined in this project, including isomorphic flux and server-side canonical URLs.  As a result, I will likely update this project with a new implementation powered by [alt](https://github.com/goatslacker/alt) and [react-router](https://github.com/rackt/react-router).

**Comment by nodegin** [comment]
is there any news about the updated version which powered by alt and react-router?

**Comment by chadpaulson** [comment]
Between the rapidly evolving React/Flux landscape and other competing interests, I have decided not to make this a priority.

That said, I do hope to revisit this project -- which is simply an example demo for some planned projects -- in a month or so.

**Comment by nodegin** [comment]
@chadpaulson I can wait for a month, this repo is the most minimal isomorphic one I seen.
